#!/bin/sh
# autostart - BASH boot script for the MR16
# This script is responsible for starting all of the necessary subsystems
# As such, it's SUPER IMPORTANT
xset -s off
xset -s noblank
unclutter -idle 0 &
cd /root/MR16/base
python V6.py &
python HUD.py &
python CMQ.py &
python ECVT.py &
