#!/bin/sh
# BASH boot script for the MR16
# This script is responsible for starting all of the necessary subsystems
# As such, it's SUPER IMPORTANT

cd ../base/
python OBD.py &
python CMQ.py &
python HUD.py &
